---
title: "COBPPreliminaryFigures_2019"
author: "Alice Stears"
date: "10/9/2019"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load packages
require(tidyverse)
require(sf)
require(leaflet)
require(wesanderson)
```
```{r}
# load dataset
setwd("~/Dropbox/Grad School/Research/Oenothera coloradensis project/Raw Data")
counts<- read.csv("./COBP_2018_data_8_29_19__all_REAL.csv", stringsAsFactors = FALSE)
sites <- read.csv("./COBP Plot Locations.csv", stringsAsFactors = FALSE)
```
```{r}
#### make a map of plot locations ####
# sites <- st_as_sf(sites, coords = c("W.Coordinate","N.Coordinate"))
# st_crs(sites) <- 4326
# leaflet(data = sites)  %>% 
#   addProviderTiles(providers$OpenStreetMap.HOT) %>% 
#   addCircles(col = "black", radius = 400, opacity = .7, weight = 2, fillColor = "#ff4500", fillOpacity = .7) %>%
#   addLegend("topleft", colors = "#ff4500", labels = "Plot Locations", opacity = .7) 
#   #535 411
```
```{r}
#### make a plot of plot density by plant type #### 
# for 2018 data
dens_2018 <- aggregate(counts$ID, by = list(counts$Plot_ID, counts$Bolting_2018), FUN = length)
names(dens_2018) <- c("Plot_ID", "Flowering", "Density")
dens_2018[dens_2018$Flowering==0,"Flowering"] <- "vegetative_18"
dens_2018[dens_2018$Flowering==1,"Flowering"] <- "reproductive_18"
names(dens_2018) <- c("Plot_ID", "DataType", "Density")
dens_2018$Year <- as.integer(2018) 
dens_2018 <- dens_2018[order(dens_2018$Plot_ID),]

# for 2019 data
dens_2019 <- aggregate(counts$ID, by = list(counts$Plot_ID, counts$Bolting_2019), FUN = length)
names(dens_2019) <- c("Plot_ID", "Flowering", "Density")
dens_2019[dens_2019$Flowering==0,"Flowering"] <- "vegetative_19"
dens_2019[dens_2019$Flowering==1,"Flowering"] <- "reproductive_19"
names(dens_2019) <- c("Plot_ID", "DataType", "Density")
dens_2019$Year <- as.integer(2019)
dens_2019 <- dens_2019[order(dens_2019$Plot_ID),]

#combine
dens <- rbind(dens_2018, dens_2019)

#read in seedling data
seeds <- read.csv("./COBP_seedlings_9_4_19.csv", stringsAsFactors = FALSE)
seedsTot <- aggregate(seeds[,c("Seedlings_18", "Seedlings_19")], by = list(seeds$Plot_ID), FUN = sum)
names(seedsTot) <- c("Plot_ID", "Density")
seedsTot$DataType <- "seedlings"
names(seedsTot) <- c("Plot_ID", "Seedlings_18", "Seedlings_19", "DataType")
#reshape seedling data frame
seedsTot <- seedsTot %>%  
  gather(key = "Type", value = c("Density"), c("Seedlings_18", "Seedlings_19"))
names(seedsTot) <- c("Plot_ID", "Type", "DataType", "Density")
seedsTot <- seedsTot[,c("Plot_ID","DataType", "Density")]
seedsTot$Year <- ifelse(str_detect(seedsTot$DataType, "_18"), 2018, 2019)

#join seedling and other plant data together
densTot <- rbind(dens, seedsTot)

#calculate total density (adult plants + seedlings)
densAll <- aggregate(dens[,c("Density")], by = list(dens$Plot_ID, dens$Year), FUN = sum)
names(densAll) <- c("Plot_ID", "Year", "Density")
densAll$DataType <- NA
densAll[densAll$Year==2018,"DataType"] <- "total_18"
densAll[densAll$Year==2019,"DataType"] <- "total_19"
densAll <- densAll[,c("Plot_ID", "DataType", "Density", "Year")]
densTot <- rbind(densTot, densAll)
densTot <- densTot[order(densTot$Plot_ID),]

densTot <- left_join(densTot, data.frame(Plot.Name=sites[,c("Plot.Name")]), by = c("Plot_ID" = "Plot.Name"))
# densTot <- st_as_sf(densTot, sf_column_name = "geometry")
densTot$SubPop <- NA
densTot[densTot$Plot_ID %in% c("C4","C5","C8"),"SubPop"] <- "Crow Creek"
densTot[densTot$Plot_ID %in% c("U3","U4","U6"),"SubPop"] <- "Unnamed"
densTot[densTot$Plot_ID %in% c("D10","D11","D7"),"SubPop"] <- "Diamond Creek"
densTot[densTot$Plot_ID %in% c("S1","S2","S3"),"SubPop"] <- "HQ5"
densTot[densTot$Plot_ID %in% c("S4","S5","S6"),"SubPop"] <- "HQ3"
densTot[densTot$Plot_ID %in% c("S7","S8","S9"),"SubPop"] <- "Meadow"

dat <- densTot[densTot$DataType %in% c("vegetative_18", "reproductive_18", "vegetative_19", "reproductive_19", "Seedlings_18", "Seedlings_19"),]
#add sub-population ID to data frame
dat <- left_join(dat, unique(counts[,c("Location","Site","Plot_ID")]), by = "Plot_ID")
#reorder dat dataframe
dat$Plot_ID <- factor(dat$Plot_ID, levels = c("C4", "C5", "C8", "D10", "D11", "D7", "U3", "U4", "U6", "S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "S9"))
dat <- dat[order(dat$Location),]

#get site-level sub-population size for 2018
SumTemp <- aggregate(dat[,c("Density")], by = list(dat$Site, dat$Year), FUN = sum) 
names(SumTemp) <- c("Site", "Year","Density")
SumTemp$Location <- NA
SumTemp[SumTemp$Site %in% c("Crow Creek", "Diamond Creek", "Unnamed Creek"), "Location"] <- "FEWAFB"
SumTemp[SumTemp$Site %in% c("HQ3", "HQ5", "Meadow"), "Location"] <- "Soapstone"

means<- aggregate(SumTemp, by = list(SumTemp$Location, SumTemp$Year), FUN = mean)
names(means) <- c("Location", "YearBad","SiteBad", "Year","MeanDensity", "LocationBad")

dat$SiteYear <- str_c(dat$Site, "_", dat$Year)

#make plot
ggplot(dat) +
  geom_bar(aes(x = SiteYear, y = Density, fill = DataType),  width = .8, stat = "identity") + 
  labs(x = "Sub Population", y = "Number of Individuals" , fill = "Life Stage") + 
  scale_fill_manual(values = c("#ff6347", "#fa2600", "#9acd32", "#6c9023", "#f9df76", "#f6ce2d")) + 
  facet_wrap("Location", scale = "free") + 
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  geom_hline(data = means[means$Year==2018,], aes(yintercept=MeanDensity),
             linetype="dashed", color = "grey30") + 
  geom_hline(data = means[means$Year==2019,], aes(yintercept=MeanDensity),
             linetype="dashed", color = "grey60") +
  ylim(c(0,1500))
```
Turns out this isn't a great way either...
```{r}
# #make a better type of plot for changes in density
# dat$class <- NA
# dat[dat$DataType %in% c("vegetative_18","vegetative_19"),"class"] <- "vegetative"
# dat[dat$DataType %in% c("reproductive_18","reproductive_19"),"class"] <- "reproductive"
# dat[dat$DataType %in% c("Seedlings_18","Seedlings_19"),"class"] <- "seedling"
# 
# plot(dat[dat$class=="vegetative","Density"]~
#        dat[dat$class=="vegetative","Year"],
#      ylab = "Plot-level Density",
#      xlab = "Year",
#      main = "Changes in plot-level density of vegetative individuals over time")
# #crow creek
# lines(x = c(2018,2019), y = c(mean(dat[dat$Site=="Crow Creek" & dat$class=="vegetative" & dat$Year==2018,"Density"]), mean(dat[dat$Site=="Crow Creek" & dat$class=="vegetative" & dat$Year==2019,"Density"])), col = "green")
# #diamond creek
# lines(x = c(2018,2019), y = c(mean(dat[dat$Site=="Diamond Creek" & dat$class=="vegetative" & dat$Year==2018,"Density"]), mean(dat[dat$Site=="Diamond Creek" & dat$class=="vegetative" & dat$Year==2019,"Density"])), col = "blue")
# #unnamed creek
# lines(x = c(2018,2019), y = c(mean(dat[dat$Site=="Unnamed Creek" & dat$class=="vegetative" & dat$Year==2018,"Density"]), mean(dat[dat$Site=="Unnamed Creek" & dat$class=="vegetative" & dat$Year==2019,"Density"])), col = "red")
# #HQ5
# lines(x = c(2018,2019), y = c(mean(dat[dat$Site=="HQ5" & dat$class=="vegetative" & dat$Year==2018,"Density"]), mean(dat[dat$Site=="HQ5" & dat$class=="vegetative" & dat$Year==2019,"Density"])), col = "orange")
# #HQ3
# lines(x = c(2018,2019), y = c(mean(dat[dat$Site=="HQ3" & dat$class=="vegetative" & dat$Year==2018,"Density"]), mean(dat[dat$Site=="HQ3" & dat$class=="vegetative" & dat$Year==2019,"Density"])), col = "brown")
# #Meadow
# lines(x = c(2018,2019), y = c(mean(dat[dat$Site=="Meadow" & dat$class=="vegetative" & dat$Year==2018,"Density"]), mean(dat[dat$Site=="Meadow" & dat$class=="vegetative" & dat$Year==2019,"Density"])), col = "black")
```   
Plot-level changes in density, accross type-classes
```{r}
par(mfrow = c(2,3))
#crow creek
plot(y = c(mean(dat[dat$Site=="Crow Creek" & dat$class=="vegetative" & dat$Year==2018,"Density"]),
           mean(dat[dat$Site=="Crow Creek" & dat$class=="vegetative" & dat$Year==2019,"Density"])),
     x = c(2018,2019),
     xlab = "year", 
     ylab = "density",
     main = "Crow Creek",
     type = "l", 
     col = "red",
     ylim = c(0,110),
     xaxt = "n")
text(2018.1, 62, "vegetative", col = "red")
lines(y = c(mean(dat[dat$Site=="Crow Creek" & dat$class=="reproductive" & dat$Year==2018,"Density"]),
           mean(dat[dat$Site=="Crow Creek" & dat$class=="reproductive" & dat$Year==2019,"Density"])),
     x = c(2018,2019),
     col = "blue")
text(2018.1,15, "reproductive", col="blue")
lines(y = c(mean(dat[dat$Site=="Crow Creek" & dat$class=="seedling" & dat$Year==2018,"Density"]),
           mean(dat[dat$Site=="Crow Creek" & dat$class=="seedling" & dat$Year==2019,"Density"])),
     x = c(2018,2019),
     col = "darkgreen")
text(2018.1,33,"seedling", col = "darkgreen")
lines( y = c(mean(dat[dat$Site=="Crow Creek" & dat$class=="seedling" & dat$Year==2018,"Density"]) + 
  mean(dat[dat$Site=="Crow Creek" & dat$class=="vegetative" & dat$Year==2018,"Density"]) + 
  mean(dat[dat$Site=="Crow Creek" & dat$class=="reproductive" & dat$Year==2018,"Density"]),
  mean(dat[dat$Site=="Crow Creek" & dat$class=="seedling" & dat$Year==2019,"Density"]) + 
  mean(dat[dat$Site=="Crow Creek" & dat$class=="vegetative" & dat$Year==2019,"Density"]) + 
  mean(dat[dat$Site=="Crow Creek" & dat$class=="reproductive" & dat$Year==2019,"Density"])),
  x = c(2018,2019))
axis(1,at = c(2018,2019), labels = c("2018", "2019"))
text(2018.1, 101, "total")

#unnamed creek
plot(y = c(mean(dat[dat$Site=="Unnamed Creek" & dat$class=="vegetative" & dat$Year==2018,"Density"]),
           mean(dat[dat$Site=="Unnamed Creek" & dat$class=="vegetative" & dat$Year==2019,"Density"])),
     x = c(2018,2019),
     xlab = "year", 
     ylab = "density",
     main = "Unnamed Creek",
     type = "l", 
     col = "red",
     ylim = c(0,450),
     xaxt = "n")
lines(y = c(mean(dat[dat$Site=="Unnamed Creek" & dat$class=="reproductive" & dat$Year==2018,"Density"]),
           mean(dat[dat$Site=="Unnamed Creek" & dat$class=="reproductive" & dat$Year==2019,"Density"])),
     x = c(2018,2019),
     col = "blue")
lines(y = c(mean(dat[dat$Site=="Unnamed Creek" & dat$class=="seedling" & dat$Year==2018,"Density"]),
           mean(dat[dat$Site=="Unnamed Creek" & dat$class=="seedling" & dat$Year==2019,"Density"])),
     x = c(2018,2019),
     col = "darkgreen")
lines( y = c(mean(dat[dat$Site=="Unnamed Creek" & dat$class=="seedling" & dat$Year==2018,"Density"]) + 
  mean(dat[dat$Site=="Unnamed Creek" & dat$class=="vegetative" & dat$Year==2018,"Density"]) + 
  mean(dat[dat$Site=="Unnamed Creek" & dat$class=="reproductive" & dat$Year==2018,"Density"]),
  mean(dat[dat$Site=="Unnamed Creek" & dat$class=="seedling" & dat$Year==2019,"Density"]) + 
  mean(dat[dat$Site=="Unnamed Creek" & dat$class=="vegetative" & dat$Year==2019,"Density"]) + 
  mean(dat[dat$Site=="Unnamed Creek" & dat$class=="reproductive" & dat$Year==2019,"Density"])),
  x = c(2018,2019))
axis(1,at = c(2018,2019), labels = c("2018", "2019"))

#Diamond creek
plot(y = c(mean(dat[dat$Site=="Diamond Creek" & dat$class=="vegetative" & dat$Year==2018,"Density"]),
           mean(dat[dat$Site=="Diamond Creek" & dat$class=="vegetative" & dat$Year==2019,"Density"])),
     x = c(2018,2019),
     xlab = "year", 
     ylab = "density",
     main = "Diamond Creek",
     type = "l", 
     col = "red",
     ylim = c(0,200),
     xaxt = "n")
lines(y = c(mean(dat[dat$Site=="Diamond Creek" & dat$class=="reproductive" & dat$Year==2018,"Density"]),
           mean(dat[dat$Site=="Diamond Creek" & dat$class=="reproductive" & dat$Year==2019,"Density"])),
     x = c(2018,2019),
     col = "blue")
lines(y = c(mean(dat[dat$Site=="Diamond Creek" & dat$class=="seedling" & dat$Year==2018,"Density"]),
           mean(dat[dat$Site=="Diamond Creek" & dat$class=="seedling" & dat$Year==2019,"Density"])),
     x = c(2018,2019),
     col = "darkgreen")
lines( y = c(mean(dat[dat$Site=="Diamond Creek" & dat$class=="seedling" & dat$Year==2018,"Density"]) + 
  mean(dat[dat$Site=="Diamond Creek" & dat$class=="vegetative" & dat$Year==2018,"Density"]) + 
  mean(dat[dat$Site=="Diamond Creek" & dat$class=="reproductive" & dat$Year==2018,"Density"]),
  mean(dat[dat$Site=="Diamond Creek" & dat$class=="seedling" & dat$Year==2019,"Density"]) + 
  mean(dat[dat$Site=="Diamond Creek" & dat$class=="vegetative" & dat$Year==2019,"Density"]) + 
  mean(dat[dat$Site=="Diamond Creek" & dat$class=="reproductive" & dat$Year==2019,"Density"])),
  x = c(2018,2019))
axis(1,at = c(2018,2019), labels = c("2018", "2019"))

#HQ5
plot(y = c(mean(dat[dat$Site=="HQ5" & dat$class=="vegetative" & dat$Year==2018,"Density"]),
           mean(dat[dat$Site=="HQ5" & dat$class=="vegetative" & dat$Year==2019,"Density"])),
     x = c(2018,2019),
     xlab = "year", 
     ylab = "density",
     main = "HQ5",
     type = "l", 
     col = "red",
     ylim = c(0,500),
     xaxt = "n")
lines(y = c(mean(dat[dat$Site=="HQ5" & dat$class=="reproductive" & dat$Year==2018,"Density"]),
           mean(dat[dat$Site=="HQ5" & dat$class=="reproductive" & dat$Year==2019,"Density"])),
     x = c(2018,2019),
     col = "blue")
lines(y = c(mean(dat[dat$Site=="HQ5" & dat$class=="seedling" & dat$Year==2018,"Density"]),
           mean(dat[dat$Site=="HQ5" & dat$class=="seedling" & dat$Year==2019,"Density"])),
     x = c(2018,2019),
     col = "darkgreen")
lines( y = c(mean(dat[dat$Site=="HQ5" & dat$class=="seedling" & dat$Year==2018,"Density"]) + 
  mean(dat[dat$Site=="HQ5" & dat$class=="vegetative" & dat$Year==2018,"Density"]) + 
  mean(dat[dat$Site=="HQ5" & dat$class=="reproductive" & dat$Year==2018,"Density"]),
  mean(dat[dat$Site=="HQ5" & dat$class=="seedling" & dat$Year==2019,"Density"]) + 
  mean(dat[dat$Site=="HQ5" & dat$class=="vegetative" & dat$Year==2019,"Density"]) + 
  mean(dat[dat$Site=="HQ5" & dat$class=="reproductive" & dat$Year==2019,"Density"])),
  x = c(2018,2019))
axis(1,at = c(2018,2019), labels = c("2018", "2019"))

#HQ3
plot(y = c(mean(dat[dat$Site=="HQ3" & dat$class=="vegetative" & dat$Year==2018,"Density"]),
           mean(dat[dat$Site=="HQ3" & dat$class=="vegetative" & dat$Year==2019,"Density"])),
     x = c(2018,2019),
     xlab = "year", 
     ylab = "density",
     main = "HQ3",
     type = "l", 
     col = "red",
     ylim = c(0,150),
     xaxt = "n")
lines(y = c(mean(dat[dat$Site=="HQ3" & dat$class=="reproductive" & dat$Year==2018,"Density"]),
           mean(dat[dat$Site=="HQ3" & dat$class=="reproductive" & dat$Year==2019,"Density"])),
     x = c(2018,2019),
     col = "blue")
lines(y = c(mean(dat[dat$Site=="HQ3" & dat$class=="seedling" & dat$Year==2018,"Density"]),
           mean(dat[dat$Site=="HQ3" & dat$class=="seedling" & dat$Year==2019,"Density"])),
     x = c(2018,2019),
     col = "darkgreen")
lines( y = c(mean(dat[dat$Site=="HQ3" & dat$class=="seedling" & dat$Year==2018,"Density"]) + 
  mean(dat[dat$Site=="HQ3" & dat$class=="vegetative" & dat$Year==2018,"Density"]) + 
  mean(dat[dat$Site=="HQ3" & dat$class=="reproductive" & dat$Year==2018,"Density"]),
  mean(dat[dat$Site=="HQ3" & dat$class=="seedling" & dat$Year==2019,"Density"]) + 
  mean(dat[dat$Site=="HQ3" & dat$class=="vegetative" & dat$Year==2019,"Density"]) + 
  mean(dat[dat$Site=="HQ3" & dat$class=="reproductive" & dat$Year==2019,"Density"])),
  x = c(2018,2019))
axis(1,at = c(2018,2019), labels = c("2018", "2019"))

#Meadow
plot(y = c(mean(dat[dat$Site=="Meadow" & dat$class=="vegetative" & dat$Year==2018,"Density"]),
           mean(dat[dat$Site=="Meadow" & dat$class=="vegetative" & dat$Year==2019,"Density"])),
     x = c(2018,2019),
     xlab = "year", 
     ylab = "density",
     main = "Meadow",
     type = "l", 
     col = "red",
     ylim = c(0,30),
     xaxt = "n")
lines(y = c(mean(dat[dat$Site=="Meadow" & dat$class=="reproductive" & dat$Year==2018,"Density"]),
           mean(dat[dat$Site=="Meadow" & dat$class=="reproductive" & dat$Year==2019,"Density"])),
     x = c(2018,2019),
     col = "blue")
lines(y = c(mean(dat[dat$Site=="Meadow" & dat$class=="seedling" & dat$Year==2018,"Density"]),
           mean(dat[dat$Site=="Meadow" & dat$class=="seedling" & dat$Year==2019,"Density"])),
     x = c(2018,2019),
     col = "darkgreen")
lines( y = c(mean(dat[dat$Site=="Meadow" & dat$class=="seedling" & dat$Year==2018,"Density"]) + 
  mean(dat[dat$Site=="Meadow" & dat$class=="vegetative" & dat$Year==2018,"Density"]) + 
  mean(dat[dat$Site=="Meadow" & dat$class=="reproductive" & dat$Year==2018,"Density"]),
  mean(dat[dat$Site=="Meadow" & dat$class=="seedling" & dat$Year==2019,"Density"]) + 
  mean(dat[dat$Site=="Meadow" & dat$class=="vegetative" & dat$Year==2019,"Density"]) + 
  mean(dat[dat$Site=="Meadow" & dat$class=="reproductive" & dat$Year==2019,"Density"])),
  x = c(2018,2019))
axis(1,at = c(2018,2019), labels = c("2018", "2019"))
```

```{r}
#### Make size-class distributions by plot ####
size <- select(counts, c("Location", "Site", "Plot_ID", "Quadrant", "ID", "LongestLeaf_cm_2018", "LongestLeaf_cm_2019", "Bolting_2018", "Bolting_2019", "No_Capsules_2018"))
mu_2018 <- plyr::ddply(size, "Location", summarise, grp.mean=mean(LongestLeaf_cm_2018, na.rm = TRUE), 
                  grp.sd = sd(LongestLeaf_cm_2018, na.rm = TRUE))
mu_2019 <- plyr::ddply(size, "Location", summarise, grp.mean=mean(LongestLeaf_cm_2019, na.rm = TRUE), 
                       grp.sd = sd(LongestLeaf_cm_2019, na.rm = TRUE))
#plot for 2018 values
ggplot(counts, aes(x=LongestLeaf_cm_2018, color = Site)) + 
  theme_classic() +
  theme(panel.grid.major = element_line(colour = "grey90")) +
  labs(x = "Longest Leaf Length (cm)", y = "Density") +
  geom_vline(data = mu_2018, aes(xintercept=grp.mean),
             linetype="dashed", color = "grey40") + 
  geom_density() +
  facet_wrap(c("Location")) +
  ylim(c(0,.20)) + 
  xlim (c(1,40)) + 
  ggtitle("2018 Size Class Distribution")
#plot for 2019 values
ggplot(counts, aes(x=LongestLeaf_cm_2019, color = Site)) + 
  theme_classic() +
  theme(panel.grid.major = element_line(colour = "grey90")) +
  labs(x = "Longest Leaf Length (cm)", y = "Density") +
  geom_vline(data = mu_2019, aes(xintercept=grp.mean),
             linetype="dashed", color = "grey40") + 
  geom_density() +
  facet_wrap(c("Location")) +
  ylim(c(0,.20)) + 
  xlim (c(1,40)) + 
  ggtitle("2019 Size Class Distribution")
```
```{r}
#### Make reproductive output-by-size plot ####
flowering <-counts[counts$Flowering_2018==1,]
flowering <- flowering[is.na(flowering$Location)==FALSE,]

ggplot(flowering, aes(x =LongestLeaf_cm_2018, y = No_Capsules_2018, color = Site)) +
  theme_classic() +
  theme(panel.grid.major = element_line(colour = "grey90")) +
  geom_point(aes(alpha = .8), show.legend = FALSE) +
  labs( x = "Longest Leaf Length (cm)", y = "Number of Seed Capsules") +
  geom_smooth(method = "lm", se = FALSE) +
  facet_wrap("Location") 

dat <- counts[counts$Site=="Crow Creek",]
crowCreek<-lm(dat$No_Capsules_2018~dat$LongestLeaf_cm_2018, data=dat)
ccR <- 0.03243

dat <- counts[counts$Site=="Diamond Creek",]
diamondCreek <- lm(dat$No_Capsules_2018~dat$LongestLeaf_cm_2018, data=dat)
ddR <- 0.00066

dat <- counts[counts$Site=="Unnamed Creek",]
unnamedCreek <- lm(dat$No_Capsules_2018~dat$LongestLeaf_cm_2018, data=dat)
uuR <- 0.008302
  
dat <- counts[counts$Site=="HQ3",]
HQ3 <- lm(dat$No_Capsules_2018~dat$LongestLeaf_cm_2018, data=dat)
hq3R <- 0.2763

dat <- counts[counts$Site=="HQ5",]
HQ5 <- lm(dat$No_Capsules_2018~dat$LongestLeaf_cm_2018, data=dat)
hq5 <- 0.3212

dat <- counts[counts$Site=="Meadow",]
Meadow <- lm(dat$No_Capsules_2018~dat$LongestLeaf_cm_2018, data=dat)
meadowR <- 0.1073
```
```{r}
#### plot size in previous year by surival probability ####
# remove those plants that were reproductive in 2018
temp <- counts %>% filter(counts$Flowering_2018==0)
temp$col <- ifelse(temp$Location=="FEWAFB", "tomato", "turquoise4")

#make a model for FEWAFB
modAFB <- glm(Alive_2019 ~ LongestLeaf_cm_2018, data = temp[temp$Location=="FEWAFB",], family = binomial)
summary(modAFB)
#predict new values
newdata <- data.frame(LongestLeaf_cm_2018=seq(1,40,1))
newdata$linear.preds <- predict(modAFB,newdata)
# Transform the linear predictors into probabilities using the logistic equation
newdata$probs <- 1/(1+exp(-(newdata$linear.preds)))

#make a model for Soapstone
modSoap <- glm(Alive_2019 ~ LongestLeaf_cm_2018, data = temp[temp$Location=="Soapstone",], family = binomial)
summary(modSoap)
#predict new values
newdata2 <- data.frame(LongestLeaf_cm_2018=seq(1,40,1))
newdata2$linear.preds <- predict(modSoap,newdata2)
# Transform the linear predictors into probabilities using the logistic equation
newdata2$probs <- 1/(1+exp(-(newdata2$linear.preds)))
#plot the regression
plot(temp$Alive_2019 ~ temp$LongestLeaf_cm_2018, col = temp$col, pch = 19,
     xlab = "2018 Leaf Length (cm)",
     ylab = "Alive in 2019 (0-1)")
lines(probs~LongestLeaf_cm_2018, data = newdata, col = "tomato")
lines(probs~LongestLeaf_cm_2018, data = newdata2, col = "turquoise4")
legend(28,.4, legend =c("FEWAFB", "Soapstone"),
       col = c("tomato", "turquoise4"), pch = 19, cex = .8)
text(28, .5, "y = -0.053+0.086x; p<.05", col = "tomato")
text(28, .7, "y = 1.408+0.0178x; p=0.705", col = "turquoise4")
```
```{r}
#### plot size in previous year and reproductive probability ####
# remove those plants that weren't alive in 2019
temp2 <- counts %>% filter(counts$Alive_2019==1)
temp2$col <- ifelse(temp2$Location=="FEWAFB", "tomato", "turquoise4")

#make a model for FEWAFB
mod2AFB <- glm(Bolting_2019 ~ LongestLeaf_cm_2018, data = temp2[temp2$Location=="FEWAFB",], family = binomial)
summary(mod2AFB)
#predict new values
newdata <- data.frame(LongestLeaf_cm_2018=seq(1,40,1))
newdata$linear.preds <- predict(mod2AFB,newdata)
# Transform the linear predictors into probabilities using the logistic equation
newdata$probs <- 1/(1+exp(-(newdata$linear.preds)))


#make a model for Soapstone
mod2Soap <- glm(Bolting_2019 ~ LongestLeaf_cm_2018, data = temp2[temp2$Location=="Soapstone",], family = binomial)
summary(mod2Soap)
#predict new values
newdata2 <- data.frame(LongestLeaf_cm_2018=seq(1,40,1))
newdata2$linear.preds <- predict(mod2Soap,newdata2)
# Transform the linear predictors into probabilities using the logistic equation
newdata2$probs <- 1/(1+exp(-(newdata2$linear.preds)))
#plot the regression
plot(temp2$Bolting_2019 ~ temp2$LongestLeaf_cm_2018, col = temp2$col, pch = 19,
     xlab = "2018 Leaf Length (cm)",
     ylab = "Bolting in 2019 (0-1)")
lines(probs~LongestLeaf_cm_2018, data = newdata, col = "tomato")
lines(probs~LongestLeaf_cm_2018, data = newdata2, col = "turquoise4")
legend(28,.4, legend =c("FEWAFB", "Soapstone"),
       col = c("tomato", "turquoise4"), pch = 19, cex = .8)
text(28, .5, "y = -4.3987+0.2362x; p<.05", col = "tomato")
text(28, .7, "y = -4.5305+0.3415x; p<.05", col = "turquoise4")
```
```{r}
#growth from year 1 to year 2
temp3 <- filter(counts, counts$Alive_2019==1)
modSurv <- lm(log(temp3$LongestLeaf_cm_2019) ~ log(temp3$LongestLeaf_cm_2018),
       data=temp3)
plot(log(temp3$LongestLeaf_cm_2019) ~ log(temp3$LongestLeaf_cm_2018),
       data=temp3, pch = 16)
```

Make maps of reproductive individuals in 2019
```{r}
map <- counts[counts$Alive_2019==1,]
plot(map$X_cm ~ map$Y_cm)
```

